### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/pollbot-integration-tests#32]
There's been some recent problems with PollBot but I haven't heard any of that being caught from this project.

**Comment by chartjes** [comment]
Hey @peterbe -- I have not been notified of any problems resulting in tests that needed to be added to this repo.

**Comment by peterbe** [comment]
What do you want to do with this? It was by chance that I discovered this project repo. It clearly failed to alert anybody. (Real users discovered the problem)

We *could*...

1. Shut down this project.
2. Figure out why it didn't discover the problem with the Telemetry Uptake endpoint in PollBot.

Personally, I'm not particularly bothered with whichever way to go. PollBot isn't an active project and has no active maintainer. I'm just the emergency-desperation maintainer and I hope that now that I've solved the problem I won't have to look at PollBot for years. 

(All the above sounded very "dark". Sorry about that. Just trying to be efficient)

**Comment by chartjes** [comment]
Well, I have no horse in the Pollbot race. If it isn't going to be used any more then nothing else needs to be done. If it is going to be used, then whomever is in charge of Pollbot should share with me the latest set of errors and maybe we can add sufficient tests to detect these things upon deployment.

These are not unit tests for the project: they are supposed to be run whenever Pollbot is deployed.

Your comments aren't dark at all: they are very realistic ;)

**Comment by peterbe** [comment]
Where are these tests reported? Who gets notified? By email?

Can we get a history of all builds? 

You say this suite is run "upon deployment". How does that work? And would it be possible to add a thing that tests it operationally, meaning it runs like a cron job.

**Comment by chartjes** [comment]
> Where are these tests reported? Who gets notified? By email?

An email is sent to fte-ci@mozilla.com if the build fails. The last reported failure was Sep 8.


> 
> Can we get a history of all builds?

Unsure. You would have to talk to the ops folks responsible for deployments about that.


> You say this suite is run "upon deployment". How does that work? And would it be possible to add a thing that tests it operationally, meaning it runs like a cron job.

Whenever ops deploys pollbot to staging or production, a call is made to a Jenkins server that is maintained by PI. Ops passes some parameters to tell the Jenkins server what environment these tests should be run in and then these tests are executed.

The same setup is used successfully for the various versions of the Kinto stacks that are deployed to both staging and production.

I imagine something could be done to run these tests like a cron job but that is not something I have done before. It is a Jenkins job and I believe there are multiple ways to trigger them that could fit what you want.

Hope that helps.

**Comment by peterbe** [comment]
Not sure what to do here. It's hard to be opinionated about a project I didn't create or contribute to. 

Let's just keep the status quo. Next time PollBot fails and our users find out before we do, then we really need to scrutinize why this suite didn't catch it first. 

For the record, I don't know what fte-ci@mozilla.com is but next time you get something on that about PollBot, ping me. 

Back to the topic of the issue. Let's say this is still active.
